import { Breakpoint } from './Types';

export function getVjsContent() {
  return "";
}

export function getMonitorMockDatas() {
  return [
    {
      label: "方法",
      data: [
        {
          key: "ROUTE_fde0c1ce0c484930e6a479699359cf87",
          dataType: -2,
          funCode: "BizWindowInstance_FormLoadAction",
          scopeId: "1671412503000",
          parentScopeId: null,
          type: "INTERVAL",
          customClass: "type-method",
          series: 1,
          from: "2022-12-19T01:15:03.230Z",
          to: "2022-12-19T01:15:03.429Z",
          children: [
            {
              key: "RULE_ce052bdd6e182a5d30a581bf0d4d03d3",
              dataType: -1,
              parentKey: "ROUTE_fde0c1ce0c484930e6a479699359cf87",
              funCode: "BizWindowInstance_FormLoadAction",
              scopeId: "1671412503000",
              ruleCode: "PrdOpenBizWindowInstance",
              type: "INTERVAL",
              customClass: "type-rule",
              series: 2,
              from: "2022-12-19T01:15:03.232Z",
              to: "2022-12-19T01:15:03.428Z",
              children: [],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>打开业务单据实例(BR_PrdOpenBizWindowInstance1) 执行耗时信息</dt><dd>规则名称：打开业务单据实例</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：BizWindowInstance_FormLoadAction</dd><dd>耗时：<span><i class="rect-method"></i>196ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
          ],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：BizWindowInstance_FormLoadAction 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>所属窗体：BizWindowInstance</dd><dd>耗时：<span><i class="rect-method"></i>199ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "ROUTE_345d933bfc006eb1bd4140b49fe3887c",
          dataType: -2,
          funCode: "API_AfterOpenBizFrameWindowEvent",
          scopeId: "52e99b728c020930a6e7c446de8e5c06",
          parentScopeId: "1671412503000",
          type: "INTERVAL",
          customClass: "type-method",
          series: 1,
          from: "2022-12-19T01:15:03.359Z",
          to: "2022-12-19T01:15:03.428Z",
          children: [
            {
              key: "RULE_2ca11a82629f7e85adfaf17e9a3034bc",
              dataType: -1,
              parentKey: "ROUTE_345d933bfc006eb1bd4140b49fe3887c",
              funCode: "API_AfterOpenBizFrameWindowEvent",
              scopeId: "52e99b728c020930a6e7c446de8e5c06",
              ruleCode: "ExecuteRuleSet",
              type: "INTERVAL",
              customClass: "type-rule",
              series: 2,
              from: "2022-12-19T01:15:03.360Z",
              to: "2022-12-19T01:15:03.428Z",
              children: [
                {
                  key: "ROUTE_b142380cf708a8d553b347788ff42b5c",
                  dataType: -2,
                  parentKey: "RULE_2ca11a82629f7e85adfaf17e9a3034bc",
                  funCode: "SPI_AfterOpenBizFrameWindowEvent",
                  scopeId: "df6bcec7e3b5cca041d000555aa4ae74",
                  parentScopeId: "52e99b728c020930a6e7c446de8e5c06",
                  type: "INTERVAL",
                  customClass: "type-method",
                  series: 1,
                  from: "2022-12-19T01:15:03.366Z",
                  to: "2022-12-19T01:15:03.428Z",
                  children: [
                    {
                      key: "RULE_8dc389f339fe89f3304587073fa7cfb5",
                      dataType: -1,
                      parentKey: "ROUTE_b142380cf708a8d553b347788ff42b5c",
                      funCode: "SPI_AfterOpenBizFrameWindowEvent",
                      scopeId: "df6bcec7e3b5cca041d000555aa4ae74",
                      ruleCode: "ExecuteRuleSet",
                      type: "INTERVAL",
                      customClass: "type-rule",
                      series: 2,
                      from: "2022-12-19T01:15:03.366Z",
                      to: "2022-12-19T01:15:03.427Z",
                      children: [
                        {
                          key: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          dataType: -2,
                          parentKey: "RULE_8dc389f339fe89f3304587073fa7cfb5",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          parentScopeId: "1671412503000",
                          type: "INTERVAL",
                          customClass: "type-method",
                          series: 1,
                          from: "2022-12-19T01:15:03.369Z",
                          to: "2022-12-19T01:15:03.421Z",
                          children: [
                            {
                              key: "RULE_87914986b317dac7833e791bb841e0fc",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "SetEntityVarControlValue",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.373Z",
                              to: "2022-12-19T01:15:03.376Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取是否已赋值(BR_SetEntityVarControlValue2) 执行耗时信息</dt><dd>规则名称：获取是否已赋值</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>3ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_2651ea84340b638e98988270b328c2cf",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "ExecExpression",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.378Z",
                              to: "2022-12-19T01:15:03.379Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>赋值EP已执行(BR_ExecExpression1) 执行耗时信息</dt><dd>规则名称：赋值EP已执行</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_56cd43d346391eddfb02254842e97a54",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "ExecuteRuleSet",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.380Z",
                              to: "2022-12-19T01:15:03.400Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>解析业务框架菜单(BR_ExecuteRuleSet2) 执行耗时信息</dt><dd>规则名称：解析业务框架菜单</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>20ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_dd3206609807d33f89c22519313cb801",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "CopyEntityRecord",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.401Z",
                              to: "2022-12-19T01:15:03.405Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取显示的按钮组(BR_CopyEntityRecord1) 执行耗时信息</dt><dd>规则名称：获取显示的按钮组</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>4ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_efc2e236df2f641ba23d743628349a36",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "SetControlPropertys",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.406Z",
                              to: "2022-12-19T01:15:03.408Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>按钮组不显示(BR_SetControlPropertys2) 执行耗时信息</dt><dd>规则名称：按钮组不显示</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>2ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_03e2f9d1c27632a9fec576879ffc0e6e",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "SetEntityVarControlValue",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.408Z",
                              to: "2022-12-19T01:15:03.409Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>赋值业务窗体编码(BR_SetEntityVarControlValue1) 执行耗时信息</dt><dd>规则名称：赋值业务窗体编码</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_0f3f7ed70f1b59862ec4d5321893f23b",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "PrdOpenBizWindowReturnData",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.410Z",
                              to: "2022-12-19T01:15:03.413Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>打开业务窗体(BR_PrdOpenBizWindowReturnData2) 执行耗时信息</dt><dd>规则名称：打开业务窗体</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>3ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_f859d7072aad1d6d0633d55b28ee4493",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "CopyEntityRecord",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.414Z",
                              to: "2022-12-19T01:15:03.415Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>权限设置(BR_CopyEntityRecord2) 执行耗时信息</dt><dd>规则名称：权限设置</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_74550e7fa7c6ccf4c9734fdc70faf508",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "SetControlPropertys",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.415Z",
                              to: "2022-12-19T01:15:03.419Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>按钮组使能(BR_SetControlPropertys1) 执行耗时信息</dt><dd>规则名称：按钮组使能</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>4ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_5a9e52bc709578fd9a8d3541be8d2235",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "ClearInterfaceEntityData",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.419Z",
                              to: "2022-12-19T01:15:03.420Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>清除界面实体中的数据(BR_ClearInterfaceEntityData1) 执行耗时信息</dt><dd>规则名称：清除界面实体中的数据</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_8557f20900205bf71373c2ddd671ef72",
                              dataType: -1,
                              parentKey:
                                "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "acb4d2248362a28f04635ced458fb061",
                              ruleCode: "CopyEntityRecord",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.420Z",
                              to: "2022-12-19T01:15:03.421Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取单据实例(BR_CopyEntityRecord1_1) 执行耗时信息</dt><dd>规则名称：获取单据实例</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                          ],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：EP_AfterOpenBizFrameWindowEvent_Impl 执行耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>所属窗体：TR_BG_Action_FrameWindow</dd><dd>耗时：<span><i class="rect-method"></i>52ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "ROUTE_cf01ed7d07bc98846016ece1295b83d3",
                          dataType: -2,
                          parentKey: "RULE_8dc389f339fe89f3304587073fa7cfb5",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "a9eb0029eb188fe34e4f2e2044f0abec",
                          parentScopeId: "1671412487000",
                          type: "INTERVAL",
                          customClass: "type-method",
                          series: 1,
                          from: "2022-12-19T01:15:03.421Z",
                          to: "2022-12-19T01:15:03.425Z",
                          children: [
                            {
                              key: "RULE_254ec249651e5968b2a6a0de778904d1",
                              dataType: -1,
                              parentKey:
                                "ROUTE_cf01ed7d07bc98846016ece1295b83d3",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "a9eb0029eb188fe34e4f2e2044f0abec",
                              ruleCode: "SetEntityVarControlValue",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.422Z",
                              to: "2022-12-19T01:15:03.422Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取是否已赋值(BR_SetEntityVarControlValue2) 执行耗时信息</dt><dd>规则名称：获取是否已赋值</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                            {
                              key: "RULE_72917bbaa62b8257d3108f88f63fbc09",
                              dataType: -1,
                              parentKey:
                                "ROUTE_cf01ed7d07bc98846016ece1295b83d3",
                              funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                              scopeId: "a9eb0029eb188fe34e4f2e2044f0abec",
                              ruleCode: "AbortRule",
                              type: "INTERVAL",
                              customClass: "type-rule",
                              series: 2,
                              from: "2022-12-19T01:15:03.424Z",
                              to: "2022-12-19T01:15:03.424Z",
                              children: [],
                              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>中断规则(BR_AbortRule1) 执行耗时信息</dt><dd>规则名称：中断规则</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                            },
                          ],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：EP_AfterOpenBizFrameWindowEvent_Impl 执行耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>所属窗体：TR_BG_Action_FrameWindow</dd><dd>耗时：<span><i class="rect-method"></i>4ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                      ],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>执行方法_EP_AfterOpenBizFrameWindowEvent(打开业务框架窗体后事件)(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：执行方法_EP_AfterOpenBizFrameWindowEvent(打开业务框架窗体后事件)</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：SPI_AfterOpenBizFrameWindowEvent</dd><dd>耗时：<span><i class="rect-method"></i>61ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                  ],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：SPI_AfterOpenBizFrameWindowEvent 执行耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>耗时：<span><i class="rect-method"></i>62ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
              ],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>执行方法_SPI_AfterOpenBizFrameWindowEvent(打开业务框架窗体后事件)(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：执行方法_SPI_AfterOpenBizFrameWindowEvent(打开业务框架窗体后事件)</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：API_AfterOpenBizFrameWindowEvent</dd><dd>耗时：<span><i class="rect-method"></i>68ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
          ],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：API_AfterOpenBizFrameWindowEvent 执行耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>耗时：<span><i class="rect-method"></i>69ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "ROUTE_51a8e801892bd51256d1e0c63c83bf41",
          dataType: -2,
          funCode: "PrdWorkFlowBizWindowMgr_FormLoadAction",
          scopeId: "10f21e0deb898776993754c9b1a95847",
          parentScopeId: "acb4d2248362a28f04635ced458fb061",
          type: "INTERVAL",
          customClass: "type-method",
          series: 1,
          from: "2022-12-19T01:15:03.799Z",
          to: "2022-12-19T01:15:03.860Z",
          children: [
            {
              key: "RULE_57279736f3be2f8bd555c865869a9c7b",
              dataType: -1,
              parentKey: "ROUTE_51a8e801892bd51256d1e0c63c83bf41",
              funCode: "PrdWorkFlowBizWindowMgr_FormLoadAction",
              scopeId: "10f21e0deb898776993754c9b1a95847",
              ruleCode: "ExecuteRuleSet",
              type: "INTERVAL",
              customClass: "type-rule",
              series: 2,
              from: "2022-12-19T01:15:03.800Z",
              to: "2022-12-19T01:15:03.860Z",
              children: [],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取待选表单目录(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：获取待选表单目录</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：PrdWorkFlowBizWindowMgr_FormLoadAction</dd><dd>耗时：<span><i class="rect-method"></i>60ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
          ],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：PrdWorkFlowBizWindowMgr_FormLoadAction 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>所属窗体：PrdVSelectedWindowMgr</dd><dd>耗时：<span><i class="rect-method"></i>61ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "ROUTE_fccbac29aa1f1ff5dbba6ce269f360e6",
          dataType: -2,
          funCode: "JGTreeView1_OnSelectIndexChanged",
          scopeId: "10f21e0deb898776993754c9b1a95847",
          parentScopeId: "acb4d2248362a28f04635ced458fb061",
          type: "INTERVAL",
          customClass: "type-method",
          series: 1,
          from: "2022-12-19T01:15:03.829Z",
          to: "2022-12-19T01:15:03.933Z",
          children: [
            {
              key: "RULE_0ee7a694b06144d2943717b4136f94bc",
              dataType: -1,
              parentKey: "ROUTE_fccbac29aa1f1ff5dbba6ce269f360e6",
              funCode: "JGTreeView1_OnSelectIndexChanged",
              scopeId: "10f21e0deb898776993754c9b1a95847",
              ruleCode: "ClearInterfaceEntityData",
              type: "INTERVAL",
              customClass: "type-rule",
              series: 2,
              from: "2022-12-19T01:15:03.829Z",
              to: "2022-12-19T01:15:03.830Z",
              children: [],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>清除界面实体中的数据(BR_ClearInterfaceEntityData1) 执行耗时信息</dt><dd>规则名称：清除界面实体中的数据</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：JGTreeView1_OnSelectIndexChanged</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
            {
              key: "RULE_583e6a1832f9b11bee2c919d48cff815",
              dataType: -1,
              parentKey: "ROUTE_fccbac29aa1f1ff5dbba6ce269f360e6",
              funCode: "JGTreeView1_OnSelectIndexChanged",
              scopeId: "10f21e0deb898776993754c9b1a95847",
              ruleCode: "ExecuteRuleSet",
              type: "INTERVAL",
              customClass: "type-rule",
              series: 2,
              from: "2022-12-19T01:15:03.830Z",
              to: "2022-12-19T01:15:03.933Z",
              children: [
                {
                  key: "ROUTE_239527b6436b1e4a49d18a898bd48807",
                  dataType: -2,
                  parentKey: "RULE_583e6a1832f9b11bee2c919d48cff815",
                  funCode: "queryWindow",
                  scopeId: "10f21e0deb898776993754c9b1a95847",
                  parentScopeId: "acb4d2248362a28f04635ced458fb061",
                  type: "INTERVAL",
                  customClass: "type-method",
                  series: 1,
                  from: "2022-12-19T01:15:03.839Z",
                  to: "2022-12-19T01:15:03.933Z",
                  children: [
                    {
                      key: "RULE_a0b19535bb6b262d8c2f3bcb9dc170a9",
                      dataType: -1,
                      parentKey: "ROUTE_239527b6436b1e4a49d18a898bd48807",
                      funCode: "queryWindow",
                      scopeId: "10f21e0deb898776993754c9b1a95847",
                      ruleCode: "SetControlPropertys",
                      type: "INTERVAL",
                      customClass: "type-rule",
                      series: 2,
                      from: "2022-12-19T01:15:03.841Z",
                      to: "2022-12-19T01:15:03.860Z",
                      children: [],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>设置当前页码1(BR_SetControlPropertys1_1) 执行耗时信息</dt><dd>规则名称：设置当前页码1</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>19ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                    {
                      key: "RULE_10c614be9013582b4a7415951e69ed4a",
                      dataType: -1,
                      parentKey: "ROUTE_239527b6436b1e4a49d18a898bd48807",
                      funCode: "queryWindow",
                      scopeId: "10f21e0deb898776993754c9b1a95847",
                      ruleCode: "ExecuteRuleSet",
                      type: "INTERVAL",
                      customClass: "type-rule",
                      series: 2,
                      from: "2022-12-19T01:15:03.861Z",
                      to: "2022-12-19T01:15:03.899Z",
                      children: [],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>执行方法_API_VQuerySelectedWindow(获取待选窗体)(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：执行方法_API_VQuerySelectedWindow(获取待选窗体)</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>38ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                    {
                      key: "RULE_fd98540f65e718daa656bbd6160f6b62",
                      dataType: -1,
                      parentKey: "ROUTE_239527b6436b1e4a49d18a898bd48807",
                      funCode: "queryWindow",
                      scopeId: "10f21e0deb898776993754c9b1a95847",
                      ruleCode: "SetControlPropertys",
                      type: "INTERVAL",
                      customClass: "type-rule",
                      series: 2,
                      from: "2022-12-19T01:15:03.900Z",
                      to: "2022-12-19T01:15:03.922Z",
                      children: [],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>分页控件赋值(BR_SetControlPropertys1) 执行耗时信息</dt><dd>规则名称：分页控件赋值</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>22ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                  ],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：queryWindow 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>所属窗体：PrdVSelectedWindowMgr</dd><dd>耗时：<span><i class="rect-method"></i>94ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
              ],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>查询窗体(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：查询窗体</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：JGTreeView1_OnSelectIndexChanged</dd><dd>耗时：<span><i class="rect-method"></i>103ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
          ],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：JGTreeView1_OnSelectIndexChanged 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>所属窗体：PrdVSelectedWindowMgr</dd><dd>耗时：<span><i class="rect-method"></i>104ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "ROUTE_2d0cedef808856c86d238f678078125c",
          dataType: -2,
          funCode: "JGTreeView1_OnSelectIndexChanged",
          scopeId: "10f21e0deb898776993754c9b1a95847",
          parentScopeId: "acb4d2248362a28f04635ced458fb061",
          type: "INTERVAL",
          customClass: "type-method",
          series: 1,
          from: "2022-12-19T01:15:03.968Z",
          to: "2022-12-19T01:15:04.055Z",
          children: [
            {
              key: "RULE_9974234b5afeeb699b98eb944dfb9cfa",
              dataType: -1,
              parentKey: "ROUTE_2d0cedef808856c86d238f678078125c",
              funCode: "JGTreeView1_OnSelectIndexChanged",
              scopeId: "10f21e0deb898776993754c9b1a95847",
              ruleCode: "ClearInterfaceEntityData",
              type: "INTERVAL",
              customClass: "type-rule",
              series: 2,
              from: "2022-12-19T01:15:03.969Z",
              to: "2022-12-19T01:15:03.969Z",
              children: [],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>清除界面实体中的数据(BR_ClearInterfaceEntityData1) 执行耗时信息</dt><dd>规则名称：清除界面实体中的数据</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：JGTreeView1_OnSelectIndexChanged</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
            {
              key: "RULE_97bfa85adcfe49fab251e985550463a0",
              dataType: -1,
              parentKey: "ROUTE_2d0cedef808856c86d238f678078125c",
              funCode: "JGTreeView1_OnSelectIndexChanged",
              scopeId: "10f21e0deb898776993754c9b1a95847",
              ruleCode: "ExecuteRuleSet",
              type: "INTERVAL",
              customClass: "type-rule",
              series: 2,
              from: "2022-12-19T01:15:03.970Z",
              to: "2022-12-19T01:15:04.055Z",
              children: [
                {
                  key: "ROUTE_4fcf2b2f2a22fdba29540620c4a06177",
                  dataType: -2,
                  parentKey: "RULE_97bfa85adcfe49fab251e985550463a0",
                  funCode: "queryWindow",
                  scopeId: "10f21e0deb898776993754c9b1a95847",
                  parentScopeId: "acb4d2248362a28f04635ced458fb061",
                  type: "INTERVAL",
                  customClass: "type-method",
                  series: 1,
                  from: "2022-12-19T01:15:03.980Z",
                  to: "2022-12-19T01:15:04.055Z",
                  children: [
                    {
                      key: "RULE_2900ac431c6b1d0bd06c3d0ec9a537a8",
                      dataType: -1,
                      parentKey: "ROUTE_4fcf2b2f2a22fdba29540620c4a06177",
                      funCode: "queryWindow",
                      scopeId: "10f21e0deb898776993754c9b1a95847",
                      ruleCode: "SetControlPropertys",
                      type: "INTERVAL",
                      customClass: "type-rule",
                      series: 2,
                      from: "2022-12-19T01:15:03.982Z",
                      to: "2022-12-19T01:15:04.000Z",
                      children: [],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>设置当前页码1(BR_SetControlPropertys1_1) 执行耗时信息</dt><dd>规则名称：设置当前页码1</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>18ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                    {
                      key: "RULE_afd1439e1da9d400950ad5942e2d2305",
                      dataType: -1,
                      parentKey: "ROUTE_4fcf2b2f2a22fdba29540620c4a06177",
                      funCode: "queryWindow",
                      scopeId: "10f21e0deb898776993754c9b1a95847",
                      ruleCode: "ExecuteRuleSet",
                      type: "INTERVAL",
                      customClass: "type-rule",
                      series: 2,
                      from: "2022-12-19T01:15:04.001Z",
                      to: "2022-12-19T01:15:04.030Z",
                      children: [],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>执行方法_API_VQuerySelectedWindow(获取待选窗体)(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：执行方法_API_VQuerySelectedWindow(获取待选窗体)</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>29ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                    {
                      key: "RULE_7c4f3af11be56d8b915a1526d53202e7",
                      dataType: -1,
                      parentKey: "ROUTE_4fcf2b2f2a22fdba29540620c4a06177",
                      funCode: "queryWindow",
                      scopeId: "10f21e0deb898776993754c9b1a95847",
                      ruleCode: "SetControlPropertys",
                      type: "INTERVAL",
                      customClass: "type-rule",
                      series: 2,
                      from: "2022-12-19T01:15:04.030Z",
                      to: "2022-12-19T01:15:04.046Z",
                      children: [],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>分页控件赋值(BR_SetControlPropertys1) 执行耗时信息</dt><dd>规则名称：分页控件赋值</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>16ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                  ],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：queryWindow 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>所属窗体：PrdVSelectedWindowMgr</dd><dd>耗时：<span><i class="rect-method"></i>75ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
              ],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>查询窗体(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：查询窗体</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：JGTreeView1_OnSelectIndexChanged</dd><dd>耗时：<span><i class="rect-method"></i>85ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
          ],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：JGTreeView1_OnSelectIndexChanged 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>所属窗体：PrdVSelectedWindowMgr</dd><dd>耗时：<span><i class="rect-method"></i>87ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
      ],
    },
    {
      label: "规则",
      data: [
        {
          key: "RULE_ce052bdd6e182a5d30a581bf0d4d03d3",
          dataType: -1,
          parentKey: "ROUTE_fde0c1ce0c484930e6a479699359cf87",
          funCode: "BizWindowInstance_FormLoadAction",
          scopeId: "1671412503000",
          ruleCode: "PrdOpenBizWindowInstance",
          type: "INTERVAL",
          customClass: "type-rule",
          series: 2,
          from: "2022-12-19T01:15:03.232Z",
          to: "2022-12-19T01:15:03.428Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>打开业务单据实例(BR_PrdOpenBizWindowInstance1) 执行耗时信息</dt><dd>规则名称：打开业务单据实例</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：BizWindowInstance_FormLoadAction</dd><dd>耗时：<span><i class="rect-method"></i>196ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RULE_2ca11a82629f7e85adfaf17e9a3034bc",
          dataType: -1,
          parentKey: "ROUTE_345d933bfc006eb1bd4140b49fe3887c",
          funCode: "API_AfterOpenBizFrameWindowEvent",
          scopeId: "52e99b728c020930a6e7c446de8e5c06",
          ruleCode: "ExecuteRuleSet",
          type: "INTERVAL",
          customClass: "type-rule",
          series: 2,
          from: "2022-12-19T01:15:03.360Z",
          to: "2022-12-19T01:15:03.428Z",
          children: [
            {
              key: "ROUTE_b142380cf708a8d553b347788ff42b5c",
              dataType: -2,
              parentKey: "RULE_2ca11a82629f7e85adfaf17e9a3034bc",
              funCode: "SPI_AfterOpenBizFrameWindowEvent",
              scopeId: "df6bcec7e3b5cca041d000555aa4ae74",
              parentScopeId: "52e99b728c020930a6e7c446de8e5c06",
              type: "INTERVAL",
              customClass: "type-method",
              series: 1,
              from: "2022-12-19T01:15:03.366Z",
              to: "2022-12-19T01:15:03.428Z",
              children: [
                {
                  key: "RULE_8dc389f339fe89f3304587073fa7cfb5",
                  dataType: -1,
                  parentKey: "ROUTE_b142380cf708a8d553b347788ff42b5c",
                  funCode: "SPI_AfterOpenBizFrameWindowEvent",
                  scopeId: "df6bcec7e3b5cca041d000555aa4ae74",
                  ruleCode: "ExecuteRuleSet",
                  type: "INTERVAL",
                  customClass: "type-rule",
                  series: 2,
                  from: "2022-12-19T01:15:03.366Z",
                  to: "2022-12-19T01:15:03.427Z",
                  children: [
                    {
                      key: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                      dataType: -2,
                      parentKey: "RULE_8dc389f339fe89f3304587073fa7cfb5",
                      funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                      scopeId: "acb4d2248362a28f04635ced458fb061",
                      parentScopeId: "1671412503000",
                      type: "INTERVAL",
                      customClass: "type-method",
                      series: 1,
                      from: "2022-12-19T01:15:03.369Z",
                      to: "2022-12-19T01:15:03.421Z",
                      children: [
                        {
                          key: "RULE_87914986b317dac7833e791bb841e0fc",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "SetEntityVarControlValue",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.373Z",
                          to: "2022-12-19T01:15:03.376Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取是否已赋值(BR_SetEntityVarControlValue2) 执行耗时信息</dt><dd>规则名称：获取是否已赋值</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>3ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_2651ea84340b638e98988270b328c2cf",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "ExecExpression",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.378Z",
                          to: "2022-12-19T01:15:03.379Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>赋值EP已执行(BR_ExecExpression1) 执行耗时信息</dt><dd>规则名称：赋值EP已执行</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_56cd43d346391eddfb02254842e97a54",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "ExecuteRuleSet",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.380Z",
                          to: "2022-12-19T01:15:03.400Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>解析业务框架菜单(BR_ExecuteRuleSet2) 执行耗时信息</dt><dd>规则名称：解析业务框架菜单</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>20ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_dd3206609807d33f89c22519313cb801",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "CopyEntityRecord",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.401Z",
                          to: "2022-12-19T01:15:03.405Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取显示的按钮组(BR_CopyEntityRecord1) 执行耗时信息</dt><dd>规则名称：获取显示的按钮组</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>4ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_efc2e236df2f641ba23d743628349a36",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "SetControlPropertys",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.406Z",
                          to: "2022-12-19T01:15:03.408Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>按钮组不显示(BR_SetControlPropertys2) 执行耗时信息</dt><dd>规则名称：按钮组不显示</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>2ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_03e2f9d1c27632a9fec576879ffc0e6e",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "SetEntityVarControlValue",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.408Z",
                          to: "2022-12-19T01:15:03.409Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>赋值业务窗体编码(BR_SetEntityVarControlValue1) 执行耗时信息</dt><dd>规则名称：赋值业务窗体编码</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_0f3f7ed70f1b59862ec4d5321893f23b",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "PrdOpenBizWindowReturnData",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.410Z",
                          to: "2022-12-19T01:15:03.413Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>打开业务窗体(BR_PrdOpenBizWindowReturnData2) 执行耗时信息</dt><dd>规则名称：打开业务窗体</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>3ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_f859d7072aad1d6d0633d55b28ee4493",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "CopyEntityRecord",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.414Z",
                          to: "2022-12-19T01:15:03.415Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>权限设置(BR_CopyEntityRecord2) 执行耗时信息</dt><dd>规则名称：权限设置</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_74550e7fa7c6ccf4c9734fdc70faf508",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "SetControlPropertys",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.415Z",
                          to: "2022-12-19T01:15:03.419Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>按钮组使能(BR_SetControlPropertys1) 执行耗时信息</dt><dd>规则名称：按钮组使能</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>4ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_5a9e52bc709578fd9a8d3541be8d2235",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "ClearInterfaceEntityData",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.419Z",
                          to: "2022-12-19T01:15:03.420Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>清除界面实体中的数据(BR_ClearInterfaceEntityData1) 执行耗时信息</dt><dd>规则名称：清除界面实体中的数据</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_8557f20900205bf71373c2ddd671ef72",
                          dataType: -1,
                          parentKey: "ROUTE_a014e4aaa5265e51ad6d63f5aee48cad",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "acb4d2248362a28f04635ced458fb061",
                          ruleCode: "CopyEntityRecord",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.420Z",
                          to: "2022-12-19T01:15:03.421Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取单据实例(BR_CopyEntityRecord1_1) 执行耗时信息</dt><dd>规则名称：获取单据实例</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                      ],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：EP_AfterOpenBizFrameWindowEvent_Impl 执行耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>所属窗体：TR_BG_Action_FrameWindow</dd><dd>耗时：<span><i class="rect-method"></i>52ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                    {
                      key: "ROUTE_cf01ed7d07bc98846016ece1295b83d3",
                      dataType: -2,
                      parentKey: "RULE_8dc389f339fe89f3304587073fa7cfb5",
                      funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                      scopeId: "a9eb0029eb188fe34e4f2e2044f0abec",
                      parentScopeId: "1671412487000",
                      type: "INTERVAL",
                      customClass: "type-method",
                      series: 1,
                      from: "2022-12-19T01:15:03.421Z",
                      to: "2022-12-19T01:15:03.425Z",
                      children: [
                        {
                          key: "RULE_254ec249651e5968b2a6a0de778904d1",
                          dataType: -1,
                          parentKey: "ROUTE_cf01ed7d07bc98846016ece1295b83d3",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "a9eb0029eb188fe34e4f2e2044f0abec",
                          ruleCode: "SetEntityVarControlValue",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.422Z",
                          to: "2022-12-19T01:15:03.422Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取是否已赋值(BR_SetEntityVarControlValue2) 执行耗时信息</dt><dd>规则名称：获取是否已赋值</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                        {
                          key: "RULE_72917bbaa62b8257d3108f88f63fbc09",
                          dataType: -1,
                          parentKey: "ROUTE_cf01ed7d07bc98846016ece1295b83d3",
                          funCode: "EP_AfterOpenBizFrameWindowEvent_Impl",
                          scopeId: "a9eb0029eb188fe34e4f2e2044f0abec",
                          ruleCode: "AbortRule",
                          type: "INTERVAL",
                          customClass: "type-rule",
                          series: 2,
                          from: "2022-12-19T01:15:03.424Z",
                          to: "2022-12-19T01:15:03.424Z",
                          children: [],
                          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>中断规则(BR_AbortRule1) 执行耗时信息</dt><dd>规则名称：中断规则</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：EP_AfterOpenBizFrameWindowEvent_Impl</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                        },
                      ],
                      dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：EP_AfterOpenBizFrameWindowEvent_Impl 执行耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>所属窗体：TR_BG_Action_FrameWindow</dd><dd>耗时：<span><i class="rect-method"></i>4ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                    },
                  ],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>执行方法_EP_AfterOpenBizFrameWindowEvent(打开业务框架窗体后事件)(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：执行方法_EP_AfterOpenBizFrameWindowEvent(打开业务框架窗体后事件)</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：SPI_AfterOpenBizFrameWindowEvent</dd><dd>耗时：<span><i class="rect-method"></i>61ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
              ],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：SPI_AfterOpenBizFrameWindowEvent 执行耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>耗时：<span><i class="rect-method"></i>62ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
          ],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>执行方法_SPI_AfterOpenBizFrameWindowEvent(打开业务框架窗体后事件)(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：执行方法_SPI_AfterOpenBizFrameWindowEvent(打开业务框架窗体后事件)</dd><dd>所属构件：vbase_prdbizframe</dd><dd>所属方法：API_AfterOpenBizFrameWindowEvent</dd><dd>耗时：<span><i class="rect-method"></i>68ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RULE_57279736f3be2f8bd555c865869a9c7b",
          dataType: -1,
          parentKey: "ROUTE_51a8e801892bd51256d1e0c63c83bf41",
          funCode: "PrdWorkFlowBizWindowMgr_FormLoadAction",
          scopeId: "10f21e0deb898776993754c9b1a95847",
          ruleCode: "ExecuteRuleSet",
          type: "INTERVAL",
          customClass: "type-rule",
          series: 2,
          from: "2022-12-19T01:15:03.800Z",
          to: "2022-12-19T01:15:03.860Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>获取待选表单目录(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：获取待选表单目录</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：PrdWorkFlowBizWindowMgr_FormLoadAction</dd><dd>耗时：<span><i class="rect-method"></i>60ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RULE_0ee7a694b06144d2943717b4136f94bc",
          dataType: -1,
          parentKey: "ROUTE_fccbac29aa1f1ff5dbba6ce269f360e6",
          funCode: "JGTreeView1_OnSelectIndexChanged",
          scopeId: "10f21e0deb898776993754c9b1a95847",
          ruleCode: "ClearInterfaceEntityData",
          type: "INTERVAL",
          customClass: "type-rule",
          series: 2,
          from: "2022-12-19T01:15:03.829Z",
          to: "2022-12-19T01:15:03.830Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>清除界面实体中的数据(BR_ClearInterfaceEntityData1) 执行耗时信息</dt><dd>规则名称：清除界面实体中的数据</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：JGTreeView1_OnSelectIndexChanged</dd><dd>耗时：<span><i class="rect-method"></i>1ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RULE_583e6a1832f9b11bee2c919d48cff815",
          dataType: -1,
          parentKey: "ROUTE_fccbac29aa1f1ff5dbba6ce269f360e6",
          funCode: "JGTreeView1_OnSelectIndexChanged",
          scopeId: "10f21e0deb898776993754c9b1a95847",
          ruleCode: "ExecuteRuleSet",
          type: "INTERVAL",
          customClass: "type-rule",
          series: 2,
          from: "2022-12-19T01:15:03.830Z",
          to: "2022-12-19T01:15:03.933Z",
          children: [
            {
              key: "ROUTE_239527b6436b1e4a49d18a898bd48807",
              dataType: -2,
              parentKey: "RULE_583e6a1832f9b11bee2c919d48cff815",
              funCode: "queryWindow",
              scopeId: "10f21e0deb898776993754c9b1a95847",
              parentScopeId: "acb4d2248362a28f04635ced458fb061",
              type: "INTERVAL",
              customClass: "type-method",
              series: 1,
              from: "2022-12-19T01:15:03.839Z",
              to: "2022-12-19T01:15:03.933Z",
              children: [
                {
                  key: "RULE_a0b19535bb6b262d8c2f3bcb9dc170a9",
                  dataType: -1,
                  parentKey: "ROUTE_239527b6436b1e4a49d18a898bd48807",
                  funCode: "queryWindow",
                  scopeId: "10f21e0deb898776993754c9b1a95847",
                  ruleCode: "SetControlPropertys",
                  type: "INTERVAL",
                  customClass: "type-rule",
                  series: 2,
                  from: "2022-12-19T01:15:03.841Z",
                  to: "2022-12-19T01:15:03.860Z",
                  children: [],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>设置当前页码1(BR_SetControlPropertys1_1) 执行耗时信息</dt><dd>规则名称：设置当前页码1</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>19ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
                {
                  key: "RULE_10c614be9013582b4a7415951e69ed4a",
                  dataType: -1,
                  parentKey: "ROUTE_239527b6436b1e4a49d18a898bd48807",
                  funCode: "queryWindow",
                  scopeId: "10f21e0deb898776993754c9b1a95847",
                  ruleCode: "ExecuteRuleSet",
                  type: "INTERVAL",
                  customClass: "type-rule",
                  series: 2,
                  from: "2022-12-19T01:15:03.861Z",
                  to: "2022-12-19T01:15:03.899Z",
                  children: [],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>执行方法_API_VQuerySelectedWindow(获取待选窗体)(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：执行方法_API_VQuerySelectedWindow(获取待选窗体)</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>38ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
                {
                  key: "RULE_fd98540f65e718daa656bbd6160f6b62",
                  dataType: -1,
                  parentKey: "ROUTE_239527b6436b1e4a49d18a898bd48807",
                  funCode: "queryWindow",
                  scopeId: "10f21e0deb898776993754c9b1a95847",
                  ruleCode: "SetControlPropertys",
                  type: "INTERVAL",
                  customClass: "type-rule",
                  series: 2,
                  from: "2022-12-19T01:15:03.900Z",
                  to: "2022-12-19T01:15:03.922Z",
                  children: [],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>分页控件赋值(BR_SetControlPropertys1) 执行耗时信息</dt><dd>规则名称：分页控件赋值</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>22ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
              ],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：queryWindow 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>所属窗体：PrdVSelectedWindowMgr</dd><dd>耗时：<span><i class="rect-method"></i>94ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
          ],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>查询窗体(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：查询窗体</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：JGTreeView1_OnSelectIndexChanged</dd><dd>耗时：<span><i class="rect-method"></i>103ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RULE_9974234b5afeeb699b98eb944dfb9cfa",
          dataType: -1,
          parentKey: "ROUTE_2d0cedef808856c86d238f678078125c",
          funCode: "JGTreeView1_OnSelectIndexChanged",
          scopeId: "10f21e0deb898776993754c9b1a95847",
          ruleCode: "ClearInterfaceEntityData",
          type: "INTERVAL",
          customClass: "type-rule",
          series: 2,
          from: "2022-12-19T01:15:03.969Z",
          to: "2022-12-19T01:15:03.969Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>清除界面实体中的数据(BR_ClearInterfaceEntityData1) 执行耗时信息</dt><dd>规则名称：清除界面实体中的数据</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：JGTreeView1_OnSelectIndexChanged</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RULE_97bfa85adcfe49fab251e985550463a0",
          dataType: -1,
          parentKey: "ROUTE_2d0cedef808856c86d238f678078125c",
          funCode: "JGTreeView1_OnSelectIndexChanged",
          scopeId: "10f21e0deb898776993754c9b1a95847",
          ruleCode: "ExecuteRuleSet",
          type: "INTERVAL",
          customClass: "type-rule",
          series: 2,
          from: "2022-12-19T01:15:03.970Z",
          to: "2022-12-19T01:15:04.055Z",
          children: [
            {
              key: "ROUTE_4fcf2b2f2a22fdba29540620c4a06177",
              dataType: -2,
              parentKey: "RULE_97bfa85adcfe49fab251e985550463a0",
              funCode: "queryWindow",
              scopeId: "10f21e0deb898776993754c9b1a95847",
              parentScopeId: "acb4d2248362a28f04635ced458fb061",
              type: "INTERVAL",
              customClass: "type-method",
              series: 1,
              from: "2022-12-19T01:15:03.980Z",
              to: "2022-12-19T01:15:04.055Z",
              children: [
                {
                  key: "RULE_2900ac431c6b1d0bd06c3d0ec9a537a8",
                  dataType: -1,
                  parentKey: "ROUTE_4fcf2b2f2a22fdba29540620c4a06177",
                  funCode: "queryWindow",
                  scopeId: "10f21e0deb898776993754c9b1a95847",
                  ruleCode: "SetControlPropertys",
                  type: "INTERVAL",
                  customClass: "type-rule",
                  series: 2,
                  from: "2022-12-19T01:15:03.982Z",
                  to: "2022-12-19T01:15:04.000Z",
                  children: [],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>设置当前页码1(BR_SetControlPropertys1_1) 执行耗时信息</dt><dd>规则名称：设置当前页码1</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>18ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
                {
                  key: "RULE_afd1439e1da9d400950ad5942e2d2305",
                  dataType: -1,
                  parentKey: "ROUTE_4fcf2b2f2a22fdba29540620c4a06177",
                  funCode: "queryWindow",
                  scopeId: "10f21e0deb898776993754c9b1a95847",
                  ruleCode: "ExecuteRuleSet",
                  type: "INTERVAL",
                  customClass: "type-rule",
                  series: 2,
                  from: "2022-12-19T01:15:04.001Z",
                  to: "2022-12-19T01:15:04.030Z",
                  children: [],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>执行方法_API_VQuerySelectedWindow(获取待选窗体)(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：执行方法_API_VQuerySelectedWindow(获取待选窗体)</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>29ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
                {
                  key: "RULE_7c4f3af11be56d8b915a1526d53202e7",
                  dataType: -1,
                  parentKey: "ROUTE_4fcf2b2f2a22fdba29540620c4a06177",
                  funCode: "queryWindow",
                  scopeId: "10f21e0deb898776993754c9b1a95847",
                  ruleCode: "SetControlPropertys",
                  type: "INTERVAL",
                  customClass: "type-rule",
                  series: 2,
                  from: "2022-12-19T01:15:04.030Z",
                  to: "2022-12-19T01:15:04.046Z",
                  children: [],
                  dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>分页控件赋值(BR_SetControlPropertys1) 执行耗时信息</dt><dd>规则名称：分页控件赋值</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：queryWindow</dd><dd>耗时：<span><i class="rect-method"></i>16ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
                },
              ],
              dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>方法：queryWindow 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>所属窗体：PrdVSelectedWindowMgr</dd><dd>耗时：<span><i class="rect-method"></i>75ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
            },
          ],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>查询窗体(BR_ExecuteRuleSet1) 执行耗时信息</dt><dd>规则名称：查询窗体</dd><dd>所属构件：vbase_prd_mgr</dd><dd>所属方法：JGTreeView1_OnSelectIndexChanged</dd><dd>耗时：<span><i class="rect-method"></i>85ms</span></dd><dd class="double-click-desc" style="text-align:center;">双击查看详情</dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
      ],
    },
    {
      label: "窗体",
      data: [
        {
          key: "WINLOAD_2e4c55f8a2c64b25a62ded8e4e1462cf",
          dataType: -3,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.186Z",
          to: "2022-12-19T01:15:03.186Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：BizWindowInstance 加载耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "WINRENDER_0ee3db2dc316c4ea05b471802564f90a",
          dataType: -4,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.186Z",
          to: "2022-12-19T01:15:03.186Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：BizWindowInstance 渲染耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "WININIT_aeaf61346521dbe91ef3a7eb6c451c5e",
          dataType: -5,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.213Z",
          to: "2022-12-19T01:15:03.243Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：BizWindowInstance 初始化耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>耗时：<span><i class="rect-method"></i>30ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "WINLOAD_9166367145f285b3980b5063a354f7b3",
          dataType: -3,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.326Z",
          to: "2022-12-19T01:15:03.326Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：TR_BG_Action_FrameWindow 加载耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "WINRENDER_c85a194104abe8b2672705e24404be3e",
          dataType: -4,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.326Z",
          to: "2022-12-19T01:15:03.326Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：TR_BG_Action_FrameWindow 渲染耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "WININIT_dee1870ca3f61e511203eed82d778c70",
          dataType: -5,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.341Z",
          to: "2022-12-19T01:15:03.348Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：TR_BG_Action_FrameWindow 初始化耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>耗时：<span><i class="rect-method"></i>7ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "WINLOAD_78ffd994e05cc22710401cbd01c2bf8c",
          dataType: -3,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.737Z",
          to: "2022-12-19T01:15:03.737Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：PrdVSelectedWindowMgr 加载耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "WINRENDER_1c65640db115a2e0e18892f45b0d09db",
          dataType: -4,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.737Z",
          to: "2022-12-19T01:15:03.737Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：PrdVSelectedWindowMgr 渲染耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>耗时：<span><i class="rect-method"></i>0ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "WININIT_6d34e2963e16294f37e496d4af754c26",
          dataType: -5,
          type: "INTERVAL",
          customClass: "type-win",
          series: 4,
          from: "2022-12-19T01:15:03.772Z",
          to: "2022-12-19T01:15:03.873Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>窗体：PrdVSelectedWindowMgr 初始化耗时信息</dt><dd>所属构件：vbase_prd_mgr</dd><dd>耗时：<span><i class="rect-method"></i>101ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
      ],
    },
    {
      label: "构件",
      data: [
        {
          key: "COM_589bb96a9744bf94ed0b4c87909c42a0",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.140Z",
          to: "2022-12-19T01:15:03.204Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prd_mgr 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>64ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "COM_394381134e47a6e0fc70dd9932588f4b",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.219Z",
          to: "2022-12-19T01:15:03.226Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prd_mgr 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>7ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "COM_2a1b2407b42992d273720406b77e8ffe",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.233Z",
          to: "2022-12-19T01:15:03.266Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prd_mgr_inst 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>33ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "COM_3bae44e327c24d6f0f5bdc1891c43dc4",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.312Z",
          to: "2022-12-19T01:15:03.329Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prdbizframe 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>17ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "COM_e449efee4da3919e0322f6803219b372",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.344Z",
          to: "2022-12-19T01:15:03.347Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prdbizframe 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>3ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "COM_b66dfb45fb3cbffec16f63d3e5c8da72",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.348Z",
          to: "2022-12-19T01:15:03.359Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prdbizframe 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>11ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "COM_7abf4c78e1312d373a7964fff25b3f48",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.361Z",
          to: "2022-12-19T01:15:03.366Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prdbizframe 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>5ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "COM_d5258de16748e6c8c8b43840acbb5162",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.600Z",
          to: "2022-12-19T01:15:03.771Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prd_mgr 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>171ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "COM_63b301e0dc97c667d5cba5e679a67a83",
          dataType: -6,
          type: "INTERVAL",
          customClass: "type-widget",
          series: 5,
          from: "2022-12-19T01:15:03.787Z",
          to: "2022-12-19T01:15:03.789Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>构件：vbase_prd_mgr 加载耗时信息</dt><dd>耗时：<span><i class="rect-method"></i>2ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
      ],
    },
    {
      label: "网络",
      data: [
        {
          key: "RPC_5201f3a45c653d0b442f572403518379",
          dataType: -7,
          type: "INTERVAL",
          customClass: "type-net",
          series: 3,
          from: "2022-12-19T01:15:03.268Z",
          to: "2022-12-19T01:15:03.309Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>请求：API_PermGetUseBizWindowInstancePrivilegeByInstanceCode 执行耗时信息</dt><dd>所属构件：vbase_prd_perm_api</dd><dd>耗时：<span><i class="rect-method"></i>41ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RPC_65eee5fb50ad213b426614e6d689e3a0",
          dataType: -7,
          type: "INTERVAL",
          customClass: "type-net",
          series: 3,
          from: "2022-12-19T01:15:03.381Z",
          to: "2022-12-19T01:15:03.400Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>请求：API_PrdParseBizFrameMenu 执行耗时信息</dt><dd>所属构件：vbase_prdbizframe</dd><dd>耗时：<span><i class="rect-method"></i>19ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RPC_87a74d4b7d992aa53812ced61ad0830e",
          dataType: -7,
          type: "INTERVAL",
          customClass: "type-net",
          series: 3,
          from: "2022-12-19T01:15:03.411Z",
          to: "2022-12-19T01:15:03.509Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>请求：API_PermGetUseBizWindowInstancePrivilegeByInstanceCode 执行耗时信息</dt><dd>所属构件：vbase_prd_perm_api</dd><dd>耗时：<span><i class="rect-method"></i>98ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RPC_fc279aedab7a4a96feb0f41946d02352",
          dataType: -7,
          type: "INTERVAL",
          customClass: "type-net",
          series: 3,
          from: "2022-12-19T01:15:03.802Z",
          to: "2022-12-19T01:15:03.827Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>请求：API_VQuerySelectedWindowCatalogTree 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr_api</dd><dd>耗时：<span><i class="rect-method"></i>25ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RPC_e1a8a5b51d8e556df7b78bf7c706c6a3",
          dataType: -7,
          type: "INTERVAL",
          customClass: "type-net",
          series: 3,
          from: "2022-12-19T01:15:03.863Z",
          to: "2022-12-19T01:15:03.898Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>请求：API_VQuerySelectedWindow 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr_api</dd><dd>耗时：<span><i class="rect-method"></i>35ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
        {
          key: "RPC_9d7c155bef19a8277abddaa3c9898b8e",
          dataType: -7,
          type: "INTERVAL",
          customClass: "type-net",
          series: 3,
          from: "2022-12-19T01:15:04.003Z",
          to: "2022-12-19T01:15:04.029Z",
          children: [],
          dt: '<i class="icon-arrow icon-arrow-up"></i><dl class="item-summary"><dt>请求：API_VQuerySelectedWindow 执行耗时信息</dt><dd>所属构件：vbase_prd_mgr_api</dd><dd>耗时：<span><i class="rect-method"></i>26ms</span></dd></dl><i class="icon-arrow icon-arrow-down"></i>',
        },
      ],
    },
  ];
}

export function getVjsUrlList() {
  return [
    {
      id: "1",
      url: "itop/vjs/combo/static/4028e581854bf058018552dab37a31a8_c4e7510a6b22ac01ff6fb1f06b49af46.js?vjsRequest=true&packageAliases=&vjsNames=%5B%7B%22vjs.framework.core%22%3Afalse%2C%22v_act_application%22%3Afalse%2C%22vact.vjs.framework.extension.platform.init.view.schema.window.vbase_prd_page_init.EmptyPageInit%22%3Afalse%7D%5D&condition=%7B%22clientType%22%3A%22pc%22%2C%22language%22%3A%22en-us%22%2C%22theme%22%3A%22default_theme%22%2C%22themeType%22%3A%22Default%22%2C%22isPure%22%3A%22false%22%2C%22domain%22%3Anull%7D",
    },
  ];
}

export function getVjsUrl() {
  return "itop/vjs/combo/static/4028e581854bf058018552dab37a31a8_c4e7510a6b22ac01ff6fb1f06b49af46.js?vjsRequest=true&packageAliases=&vjsNames=%5B%7B%22vjs.framework.core%22%3Afalse%2C%22v_act_application%22%3Afalse%2C%22vact.vjs.framework.extension.platform.init.view.schema.window.vbase_prd_page_init.EmptyPageInit%22%3Afalse%7D%5D&condition=%7B%22clientType%22%3A%22pc%22%2C%22language%22%3A%22en-us%22%2C%22theme%22%3A%22default_theme%22%2C%22themeType%22%3A%22Default%22%2C%22isPure%22%3A%22false%22%2C%22domain%22%3Anull%7D";
}

export function getFrontendMethods() {
  return [
    {
      componentCode: "jggrouppanel",
      componentName: "编组",
      methodCode: "JGButton1_OnClick",
      methodName: "打开窗体_单击事件",
      windowCode: "form36",
      windowName: "场景36",
    },
    {
      componentCode: "jggrouppanel",
      componentName: "编组",
      methodCode: "test",
      methodName: "测试方法",
    },
  ];
}

export function getFrontendMethod() {
  return {
    $: { type: "client" },
    ruleSets: {
      ruleSet: {
        outputs: "",
        $: {
          name: "按钮1_单击事件",
          isRuleChainVisible: "false",
          code: "JGButton1_OnClick",
          isExtendable: "false",
          desc: "",
        },
        inputs: "",
        ruleRoute: {
          $: { type: "q22:string" },
          _: '<evaluateRule code="BR_ShowMessage1" /><if> <define> <expression>True</expression> </define> <sequence> <evaluateRule code="BR_ShowMessage2" /> <if> <define> <expression>GetEntityRowCount("BR_VAR_PARENT.menu")==0GetEntityRowCount("BR_VAR_PARENT.menu")==0</expression> </define> <sequence> <evaluateRule code="BR_ShowMessage4" /> <foreach> <define> <varCode>rd</varCode> <entityType>window</entityType> <entityCode>ds</entityCode> </define> <sequence> <evaluateRule code="BR_ShowMessage5" /> </sequence> </foreach> </sequence> </if> </sequence> </if> <else> <sequence> <evaluateRule code="BR_ShowMessage3" /> </sequence> </else>',
        },
        routeContext: "",
        ruleInstances: {
          ruleInstance: [
            {
              condition: "",
              $: {
                ruleCode: "ShowMessage",
                transactionType: "none",
                instanceCode: "BR_ShowMessage1",
                isNeedLog: "False",
                instanceName: "显示设置的提示信息",
                isEnabled: "True",
                ruleName: "显示设置的提示信息",
              },
              ruleConfig:
                '{"showType":"0","time":"3","unModal":false,"simpleChinesePrompt":{"msgnote":"\\"asdfasdf\\"","type":"1"}}',
            },
            {
              condition: "",
              $: {
                ruleCode: "ShowMessage",
                transactionType: "none",
                instanceCode: "BR_ShowMessage4",
                isNeedLog: "False",
                instanceName: "显示设置的提示信息_3",
                isEnabled: "True",
                ruleName: "显示设置的提示信息",
              },
              ruleConfig:
                '{"showType":"0","time":"3","unModal":false,"simpleChinesePrompt":{"msgnote":"\\"asdfasdf\\"","type":"1"}}',
            },
            {
              condition: "",
              $: {
                ruleCode: "ShowMessage",
                transactionType: "none",
                instanceCode: "BR_ShowMessage3",
                isNeedLog: "False",
                instanceName: "显示设置的提示信息_2",
                isEnabled: "True",
                ruleName: "显示设置的提示信息",
              },
              ruleConfig:
                '{"showType":"0","time":"3","unModal":false,"simpleChinesePrompt":{"msgnote":"\\"asdfasdfasdf\\"","type":"1"}}',
            },
            {
              condition: "",
              $: {
                ruleCode: "ShowMessage",
                transactionType: "none",
                instanceCode: "BR_ShowMessage5",
                isNeedLog: "False",
                instanceName: "显示设置的提示信息_4",
                isEnabled: "True",
                ruleName: "显示设置的提示信息",
              },
              ruleConfig:
                '{"showType":"0","time":"3","unModal":false,"simpleChinesePrompt":{"msgnote":"\\"aaaaa\\"","type":"1"}}',
            },
            {
              condition: "",
              $: {
                ruleCode: "ShowMessage",
                transactionType: "none",
                instanceCode: "BR_ShowMessage2",
                isNeedLog: "False",
                instanceName: "显示设置的提示信息_1",
                isEnabled: "True",
                ruleName: "显示设置的提示信息",
              },
              ruleConfig:
                '{"showType":"0","time":"3","unModal":false,"simpleChinesePrompt":{"msgnote":"\\"adsfadsfafd\\"","type":"1"}}',
            },
            {
              condition: "",
              $: {
                ruleCode: "ExecuteRuleSet",
                transactionType: "none",
                instanceCode: "xiedh_test1.form13.JGButton1_OnClick",
                isNeedLog: "false",
                instanceName: "执行方法",
                isEnabled: "true",
                ruleName: "执行方法",
              },
              ruleConfig:
                '{"filter": null,"invokeTarget": {"sourceType": "client-ruleSet","invokeType": "local","componentCode": "xiedh_test1","windowCode": "form13","ruleSetCode": "JGButton1_OnClick"},"invokeParams": null,"returnMapping": null}',
            },
          ],
        },
      },
    },
    ruleInstances: {
      ruleInstance: {
        condition: "",
        $: {
          ruleCode: "ExecuteRuleSet",
          transactionType: "none",
          instanceCode: "xiedh_test1.form13.JGButton1_OnClick",
          isNeedLog: "false",
          instanceName: "执行方法",
          isEnabled: "true",
          ruleName: "执行方法",
        },
        ruleConfig:
          '{"filter": null,"invokeTarget": {"sourceType": "client-ruleSet","invokeType": "local","componentCode": "xiedh_test1","windowCode": "form13","ruleSetCode": "JGButton1_OnClick"},"invokeParams": null,"returnMapping": null}',
      },
    },
  };
}

let breakpoints: Breakpoint[] = [];

export function addBreakpoint(breakpoint: Breakpoint) {
  breakpoints.push(breakpoint);
}

const indexOf = function (breakpoint: Breakpoint, breakpoints: Breakpoint[]) {
  for (let index = 0; index < breakpoints.length; index++) {
    const bp = breakpoints[index];
    if (
      bp.location.componentCode == breakpoint.location.componentCode &&
      bp.location.methodCode == breakpoint.location.methodCode &&
      bp.location.ruleCode == breakpoint.location.ruleCode
    ) {
      if (
        typeof bp.location.windowCode == typeof breakpoint.location.windowCode
      ) {
        return index;
      }
    }
  }
  return -1;
};

export function removeBreakpoint(breakpoint: Breakpoint | Breakpoint[]) {
  const storage: Breakpoint[] = [];
  const removed: Breakpoint[] = Array.isArray(breakpoint)
    ? breakpoint
    : [breakpoint];
  breakpoints.forEach((bp) => {
    if (indexOf(bp, removed) == -1) {
      storage.push(bp);
    }
  });
  breakpoints = storage;
}

export function updateBreakpoint(breakpoint: Breakpoint) {
  for (let index = 0; index < breakpoints.length; index++) {
    const bp = breakpoints[index];
    if (
      bp.location.componentCode == breakpoint.location.componentCode &&
      bp.location.methodCode == breakpoint.location.methodCode &&
      bp.location.ruleCode == breakpoint.location.ruleCode
    ) {
      if (
        typeof bp.location.windowCode == typeof breakpoint.location.windowCode
      ) {
        breakpoints[index] = breakpoint;
      }
    }
  }
}

export function getBreakpoints() {
  return breakpoints.concat([]);
}

let breakAllRule = false;

export function clearBreakpoint() {
  breakpoints = [];
  breakAllRule = false;
}

export function markBreakAllRule() {
  breakAllRule = true;
}

export function isBreakAllRule() {
  return breakAllRule;
}

export function unmarkBreakAllRule() {
  breakAllRule = false;
}

let ignorebreakpoints = false;

export function markIgnoreBreakpoints() {
  ignorebreakpoints = true;
}

export function unmarkIgnoreBreakpoints() {
  ignorebreakpoints = false;
}

export function isIgnoreBreakpoints() {
  return ignorebreakpoints;
}

export function getRulesetDebugInfo() {
  return {
    输入: {
      input1: "value1",
      input2: true,
      input3: [{ fieldCode1: "fieldCode1", fieldCode2: "fieldCode2" }],
    },
    变量: {},
    输出: {},
  };
}

export function getWindowDebugInfo() {
  return {
    输入: {
      input1: "value1",
      input2: true,
      input3: [{ fieldCode1: "fieldCode1", fieldCode2: "fieldCode2" }],
    },
    输出: { output1: "value1" },
    控件: { propertys: { code: "code1" } },
  };
}

export function getRuleDebugInfo() {
  return {
    filter: null,
    invokeTarget: {
      sourceType: "client-ruleSet",
      invokeType: "local",
      componentCode: "vbase_prd_mgr",
      windowCode: "PrdSelectedPortalWinMgr",
      ruleSetCode: "JGToolbarMenu1_OnClick",
    },
    invokeParams: null,
    returnMapping: null,
  };
}
